training:
  epochs: 1
  accumulate_grad_batches: {}
siren:
  cls: SirenNet
  dim_in: 3
  dim_hidden: 256
  dim_out: 1
  n_layers: 5
  w0: 30.0
  w0initial: 30.0
  use_bias: True
  final_activation: None
encoding:
  otype: "HashGrid"
  n_levels: 16
  n_features_per_level: 2
  log2_hashmap_size: 16
  base_resolution: 16
  per_level_scale: 2
datamodule:
  _target_: MriDataModule
  cls: MriDataModule
  mri_path: "data/t2_111.nii.gz"
  output_path: "results_siren/"
  batch_size: 1
optimizer:
  _target_: FakeOptimizer
  arg1: 1
  arg2: 2
  arg3: 3

